### ISSUE TITLE
Support `yaml` 2.x

### ISSUE THREAD

**Issue by allanlewis** [ota-meshi/yaml-eslint-parser#108]
The `yaml` project released 2.x recently. The changes are [reported][1] to be largely internal:

> If you've been using the library just via its `parse()`, `parseDocument()` and `stringify()` functions, then it's quite likely that none of the changes affect your experience in any way. However, if you've been doing something more involved, then I would strongly recommend that you review the library's [documentation site](https://eemeli.org/yaml/) for the v2 docs.

[1]: https://github.com/eemeli/yaml/releases/tag/v2.0.0

It would be nice if this project supported it.

**Comment by ota-meshi** [comment]
This package is already starting to use yaml v2. #80

If you want to try it now, use v1.0.0-beta.1.

https://www.npmjs.com/package/yaml-eslint-parser/v/1.0.0-beta.1
