### ISSUE TITLE
[@antfu/eslint-config@0.25.2 › yaml-eslint-parser@^1.0.1] Can't find package yaml-eslint-parser's version: 1.1.0

### ISSUE THREAD

**Issue by liuqingcun** [ota-meshi/yaml-eslint-parser#115]
[@antfu/eslint-config@0.25.2 › yaml-eslint-parser@^1.0.1] Can't find package yaml-eslint-parser's version: 1.1.0

**Comment by liuqingcun** [comment]
An error was reported after published the 1.1.0 new package

**Comment by ota-meshi** [comment]
I don't know what you think is the problem with this package.
