### ISSUE TITLE
Don't depend on `yaml/dist/doc/directives`, or get `yaml` to export `Directives`

### ISSUE THREAD

**Issue by alecmev** [ota-meshi/yaml-eslint-parser#175]
`yaml` [doesn't export it](https://github.com/eemeli/yaml/blob/4aa56d337dc5e286eb0c9111a3b370f21e321117/package.json#L27-L39), unfortunately, so TypeScript says this with `skipLibCheck: false`:

```
node_modules/yaml-eslint-parser/lib/utils.d.ts:1:33 - error TS2307: Cannot find module 'yaml/dist/doc/directives' or its corresponding type declarations.

1 import type { Directives } from "yaml/dist/doc/directives";
```

One solution I see is to instead use [`DocumentOptions`](https://github.com/eemeli/yaml/blob/4aa56d337dc5e286eb0c9111a3b370f21e321117/src/options.ts#L86):

```ts
import type { DocumentOptions } from "yaml";
export type YAMLVersion = NonNullable<DocumentOptions['version']>
```

Another solution is to talk to `yaml` and get them to re-export `Directives` in `index.ts`.

**Comment by alecmev** [comment]
@ota-meshi Pinging, in case this fell through the cracks.

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
Hmm. Maybe the type has changed in a minor version. Would you consider opening a pull request?
