### ISSUE TITLE
Parsing breaks on perfectly valid yml files

### ISSUE THREAD

**Issue by csimi** [ota-meshi/yaml-eslint-parser#186]
For example if you copy the docker-compose file example from https://docs.docker.com/compose/compose-application-model/

  17:15  error  Parsing error: ';' expected

Line 17 contains:
```
      - db-data:/etc/data
```

Helmfiles are also pretty problematic.

**Comment by ota-meshi** [comment]
I can't reproduce the problem. Could you please share a GitHub repo where we can reproduce the issue?

**Comment by csimi** [comment]
Sorry you're right, I think for some reason the override for the parser wasn't applied correctly, probably conflicted with one of our other overrides.
Closing this.
